---
#<% require 'poise_boiler' %>
<%= PoiseBoiler.kitchen(platforms: %w{ubuntu centos-6.5}) %>

suites:
- name: default
  run_list:
  - recipe[application_ruby_test]
  - recipe[application_ruby_test::sinatra]
